mod liquidation_success;
mod liquidation_fail_not_allowed_amount;
mod liquidation_failed_on_call_with_wrong_borrow_token;
mod liquidation_fail_as_liquidator_is_borrower;
mod liquidation_fail_due_to_low_health_factor;